### ISSUE TITLE
ran the example didn't see any errors.

### ISSUE THREAD

**Issue by apmontgomery** [joostdecock/nuxtent-example#3]
Is this already fixed?  Otherwise, I'm happy to get it done today/tomorrow.

**Comment by apmontgomery** [comment]
If it isn't fixed it may work on my end because yarn has already cached my working version.

**Comment by joostdecock** [comment]
I'm currently validating the fix, but yes, it seems it's been fixed. I'll keep this open until it's confirmed

**Comment by joostdecock** [comment]
Current status: page generation no longer throws any errors, and all static pages are generated.

However, the in-app navigation is still broken. It would be great if you could look into that, as it's above my pay grade.

With this clarified, I'm closing this issue.
